In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import manifold
from sklearn import tree
from sklearn.metrics import accuracy_score as acc_rate
from sklearn.model_selection import train_test_split
import graphviz

In C:\Users\ASUS\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\ASUS\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\ASUS\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\ASUS\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\ASUS\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.


In [11]:
data = pd.read_csv('p2p.csv', index_col=0)

In [12]:
data = data.dropna()
y = data.status
data = data.drop(['status'], axis=1)

In [13]:
#reduce the data to 2D to reduce overfitting
X_r, err = manifold.locally_linear_embedding(data.dropna(), n_neighbors=15, n_components=2, random_state=0)

In [14]:
# split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_r, y.values, test_size=0.3, random_state=123)

In [15]:
# Decision Tree model
clf = tree.DecisionTreeClassifier(criterion='entropy', splitter='best')
clf.fit(X=X_train, y=y_train)
print('\nThe target test data set is:\n', y_test)
print('\nThe predicted result is:\n', clf.predict(X_test))
print('\nAccuracy rate is:\n', acc_rate(y_test, clf.predict(X_test)))


The target test data set is:
 [0. 0. 1. ... 0. 0. 0.]

The predicted result is:
 [0. 0. 0. ... 0. 0. 0.]

Accuracy rate is:
 0.876615150747403


In [17]:
#Visualize the graph
dot_data = tree.export_graphviz(clf,
                                out_file=None,
                                class_names="status",
                                filled=True,
                                rounded=True,
                                impurity=False,
                                special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("p2p", view = True)

'p2p.pdf'

In [18]:
# Method without using LLE to flatten the data structure.

feature_names = data.columns.values
X_train, X_test, y_train, y_test = train_test_split(data, y.values, test_size=0.3, random_state=123)
feature_names

array(['ratio001', 'ratio002', 'ratio003', 'ratio004', 'ratio005',
       'ratio006', 'ratio008', 'ratio011', 'ratio012', 'ratio017',
       'ratio018', 'ratio019', 'ratio027', 'ratio029', 'ratio030', 'DIO',
       'DPO', 'DSO', 'turnover', 'nace', 'ratio036', 'ratio037',
       'ratio039', 'ratio040'], dtype=object)

In [19]:
# initial an decision tree classifier object with given arguments
clf = tree.DecisionTreeClassifier(criterion='entropy', splitter='best')
clf.fit(X=X_train, y=y_train)

# make prediction
print('\nThe target test data set is:\n', y_test)
print('\nThe predicted result is:\n', clf.predict(X_test))
print('\nAccuracy rate is:\n', acc_rate(y_test, clf.predict(X_test)))

# visualizing the tree

dot_data = tree.export_graphviz(clf,
                                out_file=None,
                                feature_names=feature_names,
                                class_names="status",
                                filled=True,
                                rounded=True,
                                impurity=False,
                                special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("p2p-2", view = True)


The target test data set is:
 [0. 0. 1. ... 0. 0. 0.]

The predicted result is:
 [0. 0. 0. ... 0. 0. 1.]

Accuracy rate is:
 0.8631872308082088


'p2p-2.pdf'